### PR TITLE
implements HammingPeriodic and HanningPeriodic

### PR DESCRIPTION
**Pull request by gsgou**
closes https://github.com/swharden/FftSharp/issues/75

### CODE REVIEW

**Comment by gsgou** [comment]
@swharden are you gonna have time soon to review  and merge this PR?

**Comment by swharden** [comment]
Hi @gsgou 

Yes! I'll review this today or tomorrow 👍

**Comment by gsgou** [comment]
@swharden just pushed another commit that fixes a test case as the periodic windows are not symmetric

**Comment by gsgou** [comment]
@swharden the test should pass now. Roughly when will you have time to review and make a new release of the package?
A quick response will be helpful so i can decide if i should make a release with the fork as submodule or wait  a few days more. Tks a lot for the useful lib.

**Comment by swharden** [comment]
Hi @gsgou 

I planned to get this done yesterday but got behind, and I'm planning to get this done and released by the end of today 👍

**Comment by swharden** [comment]
> planning to get this done and released by the end of today

It's 10:30 pm here (EST) and I'm still underwater some some other projects (including cooking dinner, lol) so it's looking unlikely that this will get finished tonight after all. It's at the top of my stack for tomorrow though, and I look forward to merging #74 and #76 and deploying an updated package as soon as possible 👍

**Comment by swharden** [comment]
Note to self, this is what these new windows look like

Hamming | Hamming Periodic
---|---
image|image

Hanning | Hanning Periodic
---|---
image|image

**Comment by swharden** [comment]
@gsgou I notice that scipy accepts a `symmetrical` argument (defaults to `True`), and if set to `False` it generates a non-symmetrical periodic window. 

Rather than add two new windows, we could modify `IWindow` to add a similar argument so users can opt-in to get the periodic feature for all existing windows. What do you think of this idea?

**Comment by swharden** [comment]
> we could modify `IWindow` to add a similar argument

To keep things rolling I'll make an `IPeriodicWindow` and apply it to `Hamming` and `Hanning` and we can decide whether to bake these functions into `IWindow` later 👍

**Comment by gsgou** [comment]
> @gsgou I notice that scipy accepts a `symmetrical` argument (defaults to `True`), and if set to `False` it generates a non-symmetrical periodic window.
> 
> Rather than add two new windows, we could modify `IWindow` to add a similar argument so users can opt-in to get the periodic feature for all existing windows. What do you think of this idea?

You are using an interface common for all the windows. But not all windows take an argument for symmetrical, hamming, hanning, cosinus etc do but not the others. Therefore i used an explicit name but you may won't to refactor.

**Comment by swharden** [comment]
> IPeriodicWindow and apply it to Hamming and Hanning

I started doing this and it got messy 😝 

> Therefore i used an explicit name but you may want to refactor.

I think that's the way to go! I'll merge shortly and issue a new release tonight 👍 

Thanks again for these PRs!

**Comment by gsgou** [comment]
Your welcome. Tks for providing this tool ;)

**Pull request merged**
